name: cdk8s

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: '24'

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: '1.25'

      - name: Setup helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Install cdk8s
        run: npm install -g cdk8s-cli

      - name: Remove current manifests
        run: rm -rf ./dist

      - name: Render
        run: go run main.go

      - name: Commit changes
        id: create-commit
        run: |
          git config user.name "cdk8s-bot"
          git config user.email "cdk8s-bot@users.noreply.github.com"

          # If there are no changes, exit early
          if [ -z "$(git status -s)" ]; then
            echo "No changed files, not committing."
            exit 0
          fi

          git add .
          git commit --message "[skip ci] apply automatic changes"
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT

      - name: Push changes to the branch
        uses: DataDog/commit-headless@1186485b788f57eedaaadb19919781698b4d262f # action/v1.0.0
        if: ${{ steps.create-commit.outputs.commit != '' }}
        with:
          branch: "${{ steps.create-commit.outputs.branch }}"
          command: push
          commits: "${{ steps.create-commit.outputs.commit }}"
